// Skyreach version + in-game changelog. Newest entry first.
// The current version badge and the "what's in this build" modal read from here.
const GAME_VERSION = '0.13.0';

const CHANGELOG = [
  {
    version: '0.13.0',
    name: 'The Drift',
    date: '2026-07-27',
    notes: [
      'The sky no longer ends: past either edge of the island chain, new islands generate as you fly, forever',
      'The drift gets harsher the further out you go — better rock, better materials, meaner company',
      'Dedicated feed button: hold it beside a ridgerunner instead of fighting the hand button for it',
      'The Field scanner is passive now — anything you take, touch or fly through logs itself',
      'Visor is a survey view: stand still, pan the camera with the stick, and every other button clears out of the way',
      'Jetpack: the thruster button arms it, then you hold jump to fly. It stays armed through landings',
      'Stripped resource nodes disappear from the world instead of sitting there greyed out',
    ],
  },
  {
    version: '0.12.0',
    name: 'Stocktake',
    date: '2026-07-27',
    notes: [
      'Survey lens (2 crystal, 2 ore): the pack now counts how much of each material is still standing out there',
      'Tap Track on a material and an arrow points to the nearest deposit you have already charted, with its distance',
      'The sky chart marks every unstripped deposit in charted ground, coloured by material',
      'The camera sits noticeably closer in — the world reads at a comfortable size again',
    ],
  },
  {
    version: '0.11.0',
    name: 'Cable and Seed',
    date: '2026-07-27',
    notes: [
      'Islands are much larger — start island nearly doubled, and every island in the chain now has room to explore',
      'Resources no longer respawn: what you strip off the rock is gone, and every node pays out more for it',
      'Planter boxes: build up to 4 beds at a base and grow skyberries or fiber — the only things that come back',
      'Zipline kit (Mk2): place two anchors, string a powered cable, and ride it in either direction',
      'Feed a ridgerunner (hold the hand while carrying food) and it stops charging you for good',
      'Much less thorn on the start island — the first cliff you meet is always clear',
      'Lizard ration: lizards come back, so food can never dead-end',
    ],
  },
  {
    version: '0.10.0',
    name: 'Thorn and Shale',
    date: '2026-07-26',
    notes: [
      'Cliff patches are now tinted from the rock they sit on — subtle, but the patterns still read at a glance',
      'Razor shale: holds your weight and cuts you while you hang on it',
      'Slick rock is properly slippery — you slide down it instead of just paying more',
      'Thorn grows across cliff lips and blocks you from topping out until it is cut',
      'Thorn hook (3 stone, 2 fiber): the first tool, and the first real goal before the glider',
      'A wrecked expedition sits beside camp — search it once for supplies, scan it for the log',
      'Cut thorn pays fiber and grows back in time',
    ],
  },
  {
    version: '0.9.0',
    name: 'Reading the Rock',
    date: '2026-07-26',
    notes: [
      'Cliff faces now have routes: handholds are cheap, slick rock is brutal, rest ledges stop the drain, and crumbling rock gives way if you hang on it',
      'Your gloves glow the colour of whatever you are gripping',
      'Sky chart (map button, top right): fog-of-war of everywhere you have been, with camp, bases, relics and the summit',
      'Recipes are discovered, not listed — plans appear when you find the reason for them',
      'Sound: procedural wind that follows altitude and storms, glove hum, thunder and more. Toggle top right',
      'The camera looks ahead when you move fast, so you can see what you are gliding into',
      'The visor pulls back three times further and marks bases, relics, threats and thermals',
      'No ridgerunner on the starting island',
    ],
  },
  {
    version: '0.8.0',
    name: 'Long Night',
    date: '2026-07-26',
    notes: [
      'Day and night: the sky turns, stars come out, nightwings hunt harder and thermals go weak after dark',
      'Storms roll in with driving wind that shoves you mid-glide, and lightning that hunts anything high and exposed',
      'Sleep at a base to skip to dawn — costs food, restores energy, fuel and some health',
      'Field scanner and field log: scan 11 rocks, creatures and landmarks to fill it in',
      'Rob stingwing nests for eggs — the resident wakes up angry',
      'Skysteel appears on the highest faces and unlocks Fabricator Mk3',
      'Mk3 gear: Storm suit (lightning-proof), Ascender rig (fast, cheap climbing), Signal beacon',
      'Raise the beacon on the highest rock in the world to finish the run',
    ],
  },
  {
    version: '0.7.0',
    name: 'Wayfarer',
    date: '2026-07-26',
    notes: [
      'Outposts far out to the left and right: dense resources, wildlife and a sealed relic on each',
      'Relics are permanent trophies (never lost on death) and buy the Relic compass and Relic core (320 energy)',
      'The world no longer stops at an invisible wall — the walkable area now spans everything generated',
      'Jetpack is a toggle, not a hold; it cuts out on landing, on grabbing rock, and when the tank runs dry',
      'Buttons sit in a fixed grid: hand and jump never move, let-go and thruster stack above jump',
      'Vital bars stay visible and legible while a menu is open',
    ],
  },
  {
    version: '0.6.0',
    name: 'The Shear',
    date: '2026-07-26',
    notes: [
      'Thermals: glide into a rising column to gain altitude for free — the Thermal wing rides them hard',
      'Ridgerunners patrol island tops and charge: little damage, but they shove you off the edge',
      'Dedicated let-go button while climbing, so you can drop off a wall on purpose',
      'Range visor: craftable, toggles a far-out view of the sky for reading a route',
      'Close button now sits fixed at the bottom of every menu',
      'Hardened against the iOS long-press magnifier and text selection',
    ],
  },
  {
    version: '0.5.0',
    name: 'Livestock',
    date: '2026-07-26',
    notes: [
      'Fabricators draw materials from your pack AND the storage of any base in range',
      'Catch cliff lizards and sky trout by hand — both respawn after a while',
      'Lizards and trout are recipe ingredients: boots, armor, jets and magnets need them',
      'Jetpack (needs Glider) adds a short fuel bar and a thruster button; Ripwing jets double the tank',
      'Spring boots: double jump. Scale armor: take 45% less damage. Health kit: +45 health',
      'Flying predators are now nightwings (bat)',
    ],
  },
  {
    version: '0.4.0',
    name: 'Ground Up',
    date: '2026-07-26',
    notes: [
      'You start with bare hands — gather on foot and fabricate Magnetic gloves before any cliff will take you',
      'Small hills and stepped shelves everywhere, jumpable without gloves',
      'Death no longer drops anything in the world: your first 4 falls are free, then each one costs a quarter of your materials',
      'Playtest cheat buttons in the pack: materials, base kits, unlock all gear, refill vitals',
      'Restart moved to the top of this panel',
      'Compact inventory tiles — tap one to eat or place it',
    ],
  },
  {
    version: '0.3.0',
    name: 'Open Sky',
    date: '2026-07-26',
    notes: [
      'Cliffs no longer block you — walk in front of them, hold up to grab the face, climb anywhere on it',
      'Climb down from any cliff top by holding down; small cliff shelves you can stand on',
      'The world is remixed from a random seed on every new game (resume keeps your world)',
      'Cliff rock tiers: granite bare-handed, basalt needs Grip spikes, storm rock needs Resonant magnets',
      'Glove pulse (craftable): tap the hand near a creature to blast Stingwings and Razorbeaks away',
      'Neutral lizards live on the cliff faces and skitter away from you',
      'Guided goals and tutorial popups removed — explore; labels live in your pack',
      'Harvest button is now a hand',
    ],
  },
  {
    version: '0.2.0',
    name: 'Homestead',
    date: '2026-07-26',
    notes: [
      'Bolt bases straight onto cliff faces — open your Pack while gripping the wall and place a Base kit',
      'Cliff bases extend a deck you can stand on, turning any wall into a rest stop',
      'Storage at every base: deposit all, take back what you need',
      'Death now scatters your raw materials into a recoverable cache — climb back for them',
      'Upgrades and gear are never lost on death; you respawn at the nearest base',
      'Progress saves to your device automatically; wipe it from the changelog panel',
      'Hanging still on a wall costs far less energy — stop and plan your route',
    ],
  },
  {
    version: '0.1.1',
    name: 'Steady Hands',
    date: '2026-07-26',
    notes: [
      'Blocked double-tap zoom, pinch zoom, text selection and the iOS long-press magnifier',
      'Buttons respond instantly to taps; crafting panels still scroll normally',
    ],
  },
  {
    version: '0.1.0',
    name: 'First Climb',
    date: '2026-07-26',
    notes: [
      'Walk, jump, magnetic-glove climbing with energy drain, mantling over ledges',
      'Health, food and glove-energy vitals; fall damage; cloud-sea death and respawn',
      'Harvestable cliff resources: skyberries, fiber, stone, iron ore, sky crystal',
      'Personal fabricator: trail ration, glider, glove battery Mk1, base kit',
      'Gliding between islands (craft the glider first)',
      'Placeable base: recharge zone, respawn point, buildable Fabricator Mk2 (battery Mk2)',
      'Two threats: Stingwing on the spire cliffs, Razorbeak patrolling the gap',
      'Two islands + a summit spike to test a maxed climb; goal hints; touch + keyboard controls',
    ],
  },
];
